name: master_app
description: An app, created for masters, businesses.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.4

dependencies:
  bloc: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_modular: ^5.0.3
  easy_localization: ^3.0.1
  flutter_svg: ^1.1.1+1
  freezed_annotation: ^2.1.0
  equatable: ^2.0.3
  mask_input_formatter: ^0.0.3
  dio: ^4.0.6
  flutter_spinkit: ^5.1.0
  get_ip_address: ^0.0.5
  dart_ipify: ^1.1.1
  pin_code_fields: ^7.4.0
  
  
  
  

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
  

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/l10n/
    - assets/svg/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat/Montserrat-Light.ttf
        - weight: 300
        - asset: fonts/montserrat/Montserrat-Regular.ttf
        - weight: 400
        - asset: fonts/montserrat/Montserrat-Medium.ttf
        - weight: 500
        - asset: fonts/montserrat/Montserrat-SemiBold.ttf
        - weight: 600
        - asset: fonts/montserrat/Montserrat-Bold.ttf
        - weight: 700
        - asset: fonts/montserrat/Montserrat-ExtraBold.ttf
        - weight: 800
